export const categories = [
  "Education & Learning",
  "Business & Startups",
  "Medical & Healing",
  "Causes & Charities",
  "Family",
  "Weddings & Honeymoon",
  "Animals & Pets",
  "Special Events",
  "Creative",
  "Community",
  "Sports",
  "Other Funding",
  "Personal",
  "Religious",
  "Legal",
  "Funerals & Tributes",
  "Volunteer & Travel",
];
